/** One mockup + accent per card. Images live in /public/mockups (generated by scripts/gen-mockups.py). */
export const mockups: Record<string, { image: string; accent: string }> = {
  ilro: { image: "/mockups/ilro.svg", accent: "#2997ff" },
  scp: { image: "/mockups/scp.svg", accent: "#30d158" },
  challengers: { image: "/mockups/challengers.svg", accent: "#bf5af2" },
  rundem: { image: "/mockups/rundem.svg", accent: "#ff375f" },
  vibeshield: { image: "/mockups/vibeshield.svg", accent: "#30d158" },
  "mission-control": { image: "/mockups/mission-control.svg", accent: "#64d2ff" },
  megastudy: { image: "/mockups/megastudy.svg", accent: "#ffd60a" },
  "portfolio-2026": { image: "/mockups/portfolio-2026.svg", accent: "#5e5ce6" },
  "consulting-automation": { image: "/mockups/consulting-automation.svg", accent: "#30d158" },
  gildongmu: { image: "/mockups/gildongmu.svg", accent: "#2997ff" },
  tmt: { image: "/mockups/tmt.svg", accent: "#bf5af2" },
  littlebank: { image: "/mockups/littlebank.svg", accent: "#ff9f0a" },
}
