/**
 * One visual per card. `image` = card face; `gallery` = detail-sheet shots (first = hero).
 * Real product screenshots live in /public/shots; only projects without a real capture fall back
 * to the procedural mockups in /public/mockups (generated by scripts/gen-mockups.py).
 */
export type Visual = { image: string; accent: string; gallery?: string[]; real: boolean }

export const mockups: Record<string, Visual> = {
  ilro: { image: "/shots/ilro-lms.jpg", accent: "#2997ff", gallery: ["/shots/ilro-lms.jpg", "/shots/ilro-mathcoach.jpg"], real: true },
  scp: { image: "/shots/scp-teacher.jpg", accent: "#30d158", real: true },
  challengers: { image: "/shots/challengers-store.jpg", accent: "#ff9f0a", real: true },
  rundem: { image: "/shots/rundem-web.jpg", accent: "#30d158", gallery: ["/shots/rundem-web.jpg", "/shots/rundem-store.jpg", "/shots/rundem-console.jpg"], real: true },
  vibeshield: {
    image: "/shots/vibeshield-dashboard.jpg",
    accent: "#30d158",
    gallery: ["/shots/vibeshield-dashboard.jpg", "/shots/vibeshield-detections.jpg", "/shots/vibeshield-autofix.jpg", "/shots/vibeshield-rules.jpg"],
    real: true,
  },
  "mission-control": { image: "/shots/mission-control.jpg", accent: "#2997ff", real: true },
  megastudy: { image: "/mockups/megastudy.svg", accent: "#ffd60a", real: false },
  "portfolio-2026": { image: "/mockups/portfolio-2026.svg", accent: "#5e5ce6", real: false },
  "consulting-automation": { image: "/shots/consulting-automation.jpg", accent: "#2997ff", real: true },
  gildongmu: { image: "/mockups/gildongmu.svg", accent: "#2997ff", real: false },
  tmt: { image: "/mockups/tmt.svg", accent: "#bf5af2", real: false },
  littlebank: { image: "/mockups/littlebank.svg", accent: "#ff9f0a", real: false },
}
